/**
 * Note: This file was auto-generated by TI PinMux on 8/18/2022.
 *
 * \file   AM243x_ALX_pinmux.h
 *
 * \brief  This file contains pad configure register offsets and bit-field 
 *         value macros for different configurations,
 *
 *           BIT[21]		TXDISABLE		disable the pin's output driver
 *           BIT[18]		RXACTIVE		enable the pin's input buffer (typically kept enabled)
 *           BIT[17]		PULLTYPESEL		set the iternal resistor pull direction high or low (if enabled)
 *           BIT[16]		PULLUDEN		internal resistor disable (0 = enabled / 1 = disabled)
 *           BIT[3:0]		MUXMODE			select the desired function on the given pin
 *
 *  \copyright Copyright (CU) 2022 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

#ifndef _AM243x_ALX_PIN_MUX_H_
#define _AM243x_ALX_PIN_MUX_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include <drivers/pinmux.h>
#include <drivers/hw_include/csl_types.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
#define PIN_MODE(mode)	                (mode)
#define PINMUX_END                      (-1)

/** \brief Active mode configurations */
/** \brief Resistor enable */
#define PIN_PULL_DISABLE                (0x1U << 16U)
/** \brief Pull direction */
#define	PIN_PULL_DIRECTION              (0x1U << 17U)
/** \brief Receiver enable */
#define	PIN_INPUT_ENABLE                (0x1U << 18U)
/** \brief Driver disable */
#define	PIN_OUTPUT_DISABLE              (0x1U << 21U)
/** \brief Wakeup enable */
#define	PIN_WAKEUP_ENABLE               (0x1U << 29U)

/** \brief Pad config register offset in control module */

enum pinMainOffsets
{
	PIN_PRG1_PRU1_GPO18		 = 0x0150,
	PIN_PRG1_PRU1_GPO5		 = 0x011C,
	PIN_PRG1_PRU1_GPO8		 = 0x0128,
	PIN_PRG0_PRU1_GPO15		 = 0x01EC,
	PIN_PRG1_PRU0_GPO19		 = 0x0104,
	PIN_PRG1_PRU0_GPO17		 = 0x00FC,
	PIN_PRG1_MDIO0_MDC		 = 0x015C,
	PIN_PRG1_MDIO0_MDIO		 = 0x0158,
	PIN_PRG1_PRU0_GPO0		 = 0x00B8,
	PIN_PRG1_PRU0_GPO1		 = 0x00BC,
	PIN_PRG1_PRU0_GPO2		 = 0x00C0,
	PIN_PRG1_PRU0_GPO3		 = 0x00C4,
	PIN_PRG1_PRU0_GPO6		 = 0x00D0,
	PIN_PRG1_PRU0_GPO4		 = 0x00C8,
	PIN_PRG1_PRU0_GPO11		 = 0x00E4,
	PIN_PRG1_PRU0_GPO12		 = 0x00E8,
	PIN_PRG1_PRU0_GPO13		 = 0x00EC,
	PIN_PRG1_PRU0_GPO14		 = 0x00F0,
	PIN_PRG1_PRU0_GPO16		 = 0x00F8,
	PIN_PRG1_PRU0_GPO15		 = 0x00F4,
	PIN_PRG1_PRU1_GPO0		 = 0x0108,
	PIN_PRG1_PRU1_GPO1		 = 0x010C,
	PIN_PRG1_PRU1_GPO2		 = 0x0110,
	PIN_PRG1_PRU1_GPO3		 = 0x0114,
	PIN_PRG1_PRU1_GPO6		 = 0x0120,
	PIN_PRG1_PRU1_GPO4		 = 0x0118,
	PIN_PRG1_PRU1_GPO11		 = 0x0134,
	PIN_PRG1_PRU1_GPO12		 = 0x0138,
	PIN_PRG1_PRU1_GPO13		 = 0x013C,
	PIN_PRG1_PRU1_GPO14		 = 0x0140,
	PIN_PRG1_PRU1_GPO16		 = 0x0148,
	PIN_PRG1_PRU1_GPO15		 = 0x0144,
};

enum pinWkupOffsets
{
};

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Pinmux configuration data for the board. Auto-generated from 
           Pinmux tool. */
extern pinmuxBoardCfg_t gAM243x_ALX_MainPinmuxData[];
extern pinmuxBoardCfg_t gAM243x_ALX_WkupPinmuxData[];

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _AM243x_ALX_PIN_MUX_H_ */
