/**
* Note: This file was auto-generated by TI PinMux on 8/18/2022 at 11:19:13 AM.
*
* \file  AM243x_ALX_pinmux_data.c
*
* \brief  This file contains the pin mux configurations for the boards.
*         These are prepared based on how the peripherals are extended on
*         the boards.
*
* \copyright Copyright (CU) 2022 Texas Instruments Incorporated -
*             http://www.ti.com/
*/

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

// #include "AM243x_ALX_pinmux.h"
 #include <drivers/pinmux.h>

#ifndef TRUE
   #define TRUE 1
#endif

/** Peripheral Pin Configurations */


static Pinmux_PerCfg_t gAM243x_ALX_MainPinmuxData[] =
{
     /* MyGPIO1 -> GPIO1_38 -> D1 */
     {
         PIN_PRG0_PRU1_GPO18, PIN_MODE(7) | \
         ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
     },
     /* MyGPIO1 -> GPIO1_39 -> F3 */
     {
         PIN_PRG0_PRU1_GPO19, PIN_MODE(7) | \
         ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
     },

    /* MyGPIO1 -> GPIO0_20 -> Y15 */
    {
        PIN_PRG1_PRU1_GPO18, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPIO1 -> GPIO0_70 -> AA11 */
    {
        PIN_PRG1_PRU1_GPO5, PIN_MODE(7) | \
        ((0x50000) & (~PIN_PULL_DISABLE & ~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPIO1 -> GPIO0_73 -> W11 */
    {
        PIN_PRG1_PRU1_GPO8, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPIO2 -> GPIO1_35 -> M4 */
    {
        PIN_PRG0_PRU1_GPO15, PIN_MODE(7) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE) & (~PIN_PULL_DISABLE))
    },
    /* MyPRU_ICSSG1_IEP1 -> PRG1_IEP0_EDC_SYNC_OUT0 -> U3 */
    {
        PIN_PRG1_PRU0_GPO19, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyPRU_ICSSG1_IEP1 -> PRG1_IEP0_EDC_SYNC_OUT1 -> T2 */
    {
        PIN_PRG1_PRU0_GPO17, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyPRU_ICSSG1_MDIO1 -> PRG1_MDIO0_MDC -> W1 */
    {
        PIN_PRG1_MDIO0_MDC, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyPRU_ICSSG1_MDIO1 -> PRG1_MDIO0_MDIO -> V2 */
    {
        PIN_PRG1_MDIO0_MDIO, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_RD0 -> V4 */
    {
        PIN_PRG1_PRU0_GPO0, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_RD1 -> W5 */
    {
        PIN_PRG1_PRU0_GPO1, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_RD2 -> AA4 */
    {
        PIN_PRG1_PRU0_GPO2, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_RD3 -> Y5 */
    {
        PIN_PRG1_PRU0_GPO3, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_RXC -> Y2 */
    {
        PIN_PRG1_PRU0_GPO6, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_RX_CTL -> AA5 */
    {
        PIN_PRG1_PRU0_GPO4, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_TD0 -> V5 */
    {
        PIN_PRG1_PRU0_GPO11, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_TD1 -> W2 */
    {
        PIN_PRG1_PRU0_GPO12, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_TD2 -> V6 */
    {
        PIN_PRG1_PRU0_GPO13, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_TD3 -> AA7 */
    {
        PIN_PRG1_PRU0_GPO14, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_TXC -> W6 */
    {
        PIN_PRG1_PRU0_GPO16, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII1 -> PRG1_RGMII1_TX_CTL -> Y7 */
    {
        PIN_PRG1_PRU0_GPO15, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_RD0 -> AA10 */
    {
        PIN_PRG1_PRU1_GPO0, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_RD1 -> Y10 */
    {
        PIN_PRG1_PRU1_GPO1, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_RD2 -> Y11 */
    {
        PIN_PRG1_PRU1_GPO2, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_RD3 -> V12 */
    {
        PIN_PRG1_PRU1_GPO3, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_RXC -> V10 */
    {
        PIN_PRG1_PRU1_GPO6, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_RX_CTL -> Y12 */
    {
        PIN_PRG1_PRU1_GPO4, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_TD0 -> Y6 */
    {
        PIN_PRG1_PRU1_GPO11, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_TD1 -> AA8 */
    {
        PIN_PRG1_PRU1_GPO12, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_TD2 -> Y9 */
    {
        PIN_PRG1_PRU1_GPO13, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_TD3 -> W9 */
    {
        PIN_PRG1_PRU1_GPO14, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_TXC -> Y8 */
    {
        PIN_PRG1_PRU1_GPO16, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyPRU_ICSSG1_RGMII2 -> PRG1_RGMII2_TX_CTL -> V9 */
    {
        PIN_PRG1_PRU1_GPO15, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END, PINMUX_END}
};

/*
 * Pinmux
 */
void Pinmux_init_sorte(void)
{
    Pinmux_config(gAM243x_ALX_MainPinmuxData, PINMUX_DOMAIN_ID_MAIN);
}

